### ISSUE TITLE
Comentarios sobre el ejercicio

### ISSUE THREAD

**Issue by m4n50n** [Petrement/hmtl_postcard_excercise#1]
Hola Lola,

✔Perfecto, has hecho exactamente lo que se pedía.

☝ **Mejoras**:
- Recuerda que siempre puedes implementar CSS adicional para hacerlo más vistoso. Simplemente con añadir un padding a la postal en sí para que el título y el logo no queden pegados a los lados o añadiendo algún color al botón ya cambiaría bastante.

☝ **Consejo**: Siempre recomiendo dedicar un tiempo (el mínimo) a cada repositorio de GitHub para hacerlo más vistoso. Es posible que en algún momento alguna persona / empresa entre a verlo y ayuda bastante tener un README.md personalizado que describa brevemente el ejercicio, o que el repositorio tenga una descripción, etc... Esto es aconsejable hacerlo desde el principio porque luego raramente vuelven a editarse.

**Comment by Petrement** [comment]
Hola Jose, 

Gracias por tus comentarios. 
Lo tendré en cuenta. :)
